### ISSUE TITLE
compressToBase64 gives different result in Windows and Linux?

### ISSUE THREAD

**Issue by ingjieye** [andykras/lz-string-cpp#1]
For example, compress the Chinese character '列'
Windows gives `uhKQ` as well as the online compressor https://codepen.io/redon77/pen/zNRxpJ
However, Linux gives `KcCI6UA=`

Would this have anything to do with wstring, string, and the different encoding formats?

**Comment by andykras** [comment]
Thanks, I will take a look

**Comment by andykras** [comment]
Fixed in comit https://github.com/andykras/lz-string-cpp/commit/f0c528eb39dd453fce2de0da793b429e5e2f39ab

You need to use `std::u16string` on linux
```cpp
#include "lz-string.hpp"

#include <locale> // wstring_convert
#include <codecvt> // codecvt_utf8

int main()
{
    std::wstring_convert<std::codecvt_utf8<char16_t>, char16_t> convert;
    
    std::u16string str = lzstring::compressToBase64(u"列");

    std::cout << convert.to_bytes(str) << std::endl; // uhKQ
}
```

see, https://onlinegdb.com/pu629xgOw
